version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command:
      - start-dev


  db:
    container_name: playbank-db
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123qwe}
      POSTGRES_DB: ${POSTGRES_DB:-playbank}
      PGDATA: /data/postgres/playbank


volumes:
  postgres_volume:
    driver: local
