spring:
  # provide the db settings
  datasource:
    url: jdbc:postgresql://localhost:5433/playbank
    username: db_user
    password: 123qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt: # see config for http://localhost:8090/realms/playground/.well-known/openid-configuration
          jwk-set-uri: http://localhost:8090/realms/playground/protocol/openid-connect/certs

server:
  port: 9999

logging:
  level:
    root: info
    org:
      springframework:
        security:
          web:
            FilterChainProxy: Debug
